// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iqbqadsldcxhjppeaonr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlxYnFhZHNsZGN4aGpwcGVhb25yIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzgzNDAyNjUsImV4cCI6MjA1MzkxNjI2NX0.Lc-YoQvhpIUumHebZRDYFQK0RM_BeoLqvGMokjmmCbw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);